# Generated by Django 5.0.7 on 2024-07-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='booked_by',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
